[project]
name = "class-03-openrouter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai-agents[litellm]>=0.0.17",
    "rich>=14.0.0",
]
